version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws"
s3_bucket = "serverless-http-api-dyna-serverlessdeploymentbuck-3zghosk6sk4l"
s3_prefix = "todo-list-aws"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todolist-stg"
s3_bucket = "serverless-http-api-dyna-serverlessdeploymentbuck-3zghosk6sk4l"
s3_prefix = "todolist-stg"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""



[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todolist-pro"
s3_bucket = "serverless-http-api-dyna-serverlessdeploymentbuck-3zghosk6sk4l"
s3_prefix = "todolist-pro"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
