AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  todo-list-aws

  Sample SAM Template for todo-list-aws


Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        DYNAMODB_TABLE: !Sub "todosTable-${Stage}"
        ENVIRONMENT: !Ref Stage

Parameters:
  Stage:
    Type: String
    Default: default
    AllowedValues:
      - default
      - staging
      - production
    Description: Introduzca staging o production, el valor por defecto es default

Resources:
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: create.create
      Runtime: python3.8
      Role: arn:aws:iam::501043071668:role/LabRole
      Events:
        Create:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: post

  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get.get
      Runtime: python3.8
      Role: arn:aws:iam::501043071668:role/LabRole
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /todos/{id}
            Method: get

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: list.list
      Runtime: python3.8
      Role: arn:aws:iam::501043071668:role/LabRole
      Events:
        List:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: get

  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update.update
      Runtime: python3.8
      Role: arn:aws:iam::501043071668:role/LabRole
      Events:
        Update:
          Type: HttpApi
          Properties:
            Path: /todos/{id}
            Method: put

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: delete.delete
      Runtime: python3.8
      Role: arn:aws:iam::501043071668:role/LabRole
      Events:
        Delete:
          Type: HttpApi
          Properties:
            Path: /todos/{id}
            Method: delete

  TranslateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: translate.get
      Runtime: python3.8
      Role: arn:aws:iam::501043071668:role/LabRole
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /todos/{id}/{language}
            Method: get

  todosTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub "todosTable-${Stage}"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1



Outputs:
  CreateFunction:
    Description: "Create TODO Lambda Function ARN"
    Value: !GetAtt CreateFunction.Arn
  GetFunction:
    Description: "Get TODO Function ARN"
    Value: !GetAtt GetFunction.Arn
  ListFunction:
    Description: "List TODO Function ARN"
    Value: !GetAtt GetFunction.Arn
  UpdateFunction:
    Description: "Update TODO Function ARN"
    Value: !GetAtt UpdateFunction.Arn
  DeleteFunction:
    Description: "Delete TODO Function ARN"
    Value: !GetAtt DeleteFunction.Arn
  TranslateFunction:
    Description: "Delete TODO Function ARN"
    Value: !GetAtt TranslateFunction.Arn